/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./local-components/**/*.{js,ts,jsx,tsx,mdx}",
    "./node_modules/mtr-design-system/components/**/*.{js,ts,jsx,tsx}",
    "./node_modules/mtr-design-system/app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--mtr-typo-fontFamilies-body)', 'sans-serif'],
        display: ['var(--mtr-typo-fontFamilies-display)', 'sans-serif'],
        mono: ['var(--mtr-typo-fontFamilies-mono)', 'monospace'],
      },
      borderRadius: {
        'mtr-none': 'var(--mtr-radius-none)',
        'mtr-xs': 'var(--mtr-radius-xs)',
        'mtr-sm': 'var(--mtr-radius-sm)',
        'mtr-md': 'var(--mtr-radius-md)',
        'mtr-lg': 'var(--mtr-radius-lg)',
        'mtr-xl': 'var(--mtr-radius-xl)',
        'mtr-2xl': 'var(--mtr-radius-2xl)',
        'mtr-3xl': 'var(--mtr-radius-3xl)',
        'mtr-full': 'var(--mtr-radius-full)',
      },
      boxShadow: {
        'mtr-xs': 'var(--mtr-elevation-xs)',
        'mtr-sm': 'var(--mtr-elevation-sm)',
        'mtr-md': 'var(--mtr-elevation-md)',
        'mtr-lg': 'var(--mtr-elevation-lg)',
        'mtr-xl': 'var(--mtr-elevation-xl)',
        'mtr-2xl': 'var(--mtr-elevation-2xl)',
        'mtr-inner': 'var(--mtr-elevation-inner)',
        'mtr-brand': 'var(--mtr-elevation-brand)',
        'mtr-brand-lg': 'var(--mtr-elevation-brandLg)',
      },
      colors: {
        mtr: {
          brand: {
            default: 'var(--mtr-brand-default)',
            darker: 'var(--mtr-brand-darker)',
            lighter: 'var(--mtr-brand-lighter)',
          },
          accent: {
            default: 'var(--mtr-accent-default)',
            darker: 'var(--mtr-accent-darker)',
            lighter: 'var(--mtr-accent-lighter)',
          },
          surface: {
            light: 'var(--mtr-surface-light)',
            lightDarker: 'var(--mtr-surface-lightDarker)',
            dark: 'var(--mtr-surface-dark)',
            darkDarker: 'var(--mtr-surface-darkDarker)',
            'disabled-onLight': 'var(--mtr-surface-disabled-onLight)',
            'disabled-onDark': 'var(--mtr-surface-disabled-onDark)',
            info: 'var(--mtr-surface-info)',
            success: 'var(--mtr-surface-success)',
            warning: 'var(--mtr-surface-warning)',
            important: 'var(--mtr-surface-important)',
          },
          surfaceBorder: {
            info: 'var(--mtr-surfaceBorder-info)',
            success: 'var(--mtr-surfaceBorder-success)',
            warning: 'var(--mtr-surfaceBorder-warning)',
            important: 'var(--mtr-surfaceBorder-important)',
          },
          text: {
            'highEmphasis-onLight': 'var(--mtr-text-highEmphasis-onLight)',
            'highEmphasis-onDark': 'var(--mtr-text-highEmphasis-onDark)',
            'lowEmphasis-onLight': 'var(--mtr-text-lowEmphasis-onLight)',
            'lowEmphasis-onDark': 'var(--mtr-text-lowEmphasis-onDark)',
            'disabled-onLight': 'var(--mtr-text-disabled-onLight)',
            'disabled-onDark': 'var(--mtr-text-disabled-onDark)',
            'action-enabled': 'var(--mtr-text-action-enabled)',
            'action-hover': 'var(--mtr-text-action-hover)',
            'action-active': 'var(--mtr-text-action-active)',
            success: 'var(--mtr-text-success)',
            warning: 'var(--mtr-text-warning)',
            important: 'var(--mtr-text-important)',
          },
          border: {
            'lowEmphasis-onLight': 'var(--mtr-border-lowEmphasis-onLight)',
            'lowEmphasis-onDark': 'var(--mtr-border-lowEmphasis-onDark)',
            'lowEmphasis-hover-onLight': 'var(--mtr-border-lowEmphasis-hover-onLight)',
            'lowEmphasis-hover-onDark': 'var(--mtr-border-lowEmphasis-hover-onDark)',
            'midEmphasis-onLight': 'var(--mtr-border-midEmphasis-onLight)',
            'midEmphasis-onDark': 'var(--mtr-border-midEmphasis-onDark)',
            'highEmphasis-onLight': 'var(--mtr-border-highEmphasis-onLight)',
            'highEmphasis-onDark': 'var(--mtr-border-highEmphasis-onDark)',
          },
          icon: {
            'enabled-onLight': 'var(--mtr-icon-enabled-onLight)',
            'enabled-onDark': 'var(--mtr-icon-enabled-onDark)',
            'hover-onLight': 'var(--mtr-icon-hover-onLight)',
            'active-onLight': 'var(--mtr-icon-active-onLight)',
            'selected-onLight': 'var(--mtr-icon-selected-onLight)',
            'disabled-onLight': 'var(--mtr-icon-disabled-onLight)',
            'disabled-onDark': 'var(--mtr-icon-disabled-onDark)',
            'lowEmphasis-enabled-onLight': 'var(--mtr-icon-lowEmphasis-enabled-onLight)',
            'lowEmphasis-enabled-onDark': 'var(--mtr-icon-lowEmphasis-enabled-onDark)',
          },
          iconBg: {
            info: 'var(--mtr-iconBg-info)',
            'info_onDark': 'var(--mtr-iconBg-info_onDark)',
            success: 'var(--mtr-iconBg-success)',
            'success_onDark': 'var(--mtr-iconBg-success_onDark)',
            warning: 'var(--mtr-iconBg-warning)',
            'warning_onDark': 'var(--mtr-iconBg-warning_onDark)',
            important: 'var(--mtr-iconBg-important)',
            'important_onDark': 'var(--mtr-iconBg-important_onDark)',
          },
          action: {
            enabled: 'var(--mtr-action-enabled)',
            hover: 'var(--mtr-action-hover)',
            active: 'var(--mtr-action-active)',
            'important-enabled': 'var(--mtr-action-important-enabled)',
            'important-hover': 'var(--mtr-action-important-hover)',
            'important-active': 'var(--mtr-action-important-active)',
            'monochrome-onLight-enabled': 'var(--mtr-action-monochrome-onLight-enabled)',
            'monochrome-onLight-hover': 'var(--mtr-action-monochrome-onLight-hover)',
            'monochrome-onLight-active': 'var(--mtr-action-monochrome-onLight-active)',
            'monochrome-onLight-selected': 'var(--mtr-action-monochrome-onLight-selected)',
            'monochrome-onLight-disabled': 'var(--mtr-action-monochrome-onLight-disabled)',
            'monochrome-onLight-bg': 'var(--mtr-action-monochrome-onLight-bg)',
            'monochrome-onDark-enabled': 'var(--mtr-action-monochrome-onDark-enabled)',
            'monochrome-onDark-hover': 'var(--mtr-action-monochrome-onDark-hover)',
            'monochrome-onDark-bg': 'var(--mtr-action-monochrome-onDark-bg)',
          },
          status: {
            info: 'var(--mtr-status-info)',
            success: 'var(--mtr-status-success)',
            warning: 'var(--mtr-status-warning)',
            warningLight: 'var(--mtr-status-warningLight)',
            important: 'var(--mtr-status-important)',
          },
          badge: {
            info: 'var(--mtr-badge-info)',
            infoLight: 'var(--mtr-badge-infoLight)',
            success: 'var(--mtr-badge-success)',
            successLight: 'var(--mtr-badge-successLight)',
            warning: 'var(--mtr-badge-warning)',
            important: 'var(--mtr-badge-important)',
            importantLight: 'var(--mtr-badge-importantLight)',
            aqua: 'var(--mtr-badge-aqua)',
            aquaLight: 'var(--mtr-badge-aquaLight)',
            green: 'var(--mtr-badge-green)',
            greenLight: 'var(--mtr-badge-greenLight)',
            yellow: 'var(--mtr-badge-yellow)',
            yellowLight: 'var(--mtr-badge-yellowLight)',
            fuschia: 'var(--mtr-badge-fuschia)',
            fuschiaLight: 'var(--mtr-badge-fuschiaLight)',
            purple: 'var(--mtr-badge-purple)',
            purpleLight: 'var(--mtr-badge-purpleLight)',
            charcoal: 'var(--mtr-badge-charcoal)',
            charcoalLight: 'var(--mtr-badge-charcoalLight)',
          },
          hover: {
            onLight: 'var(--mtr-hover-onLight)',
            onDark: 'var(--mtr-hover-onDark)',
          },
          selected: {
            onLight: 'var(--mtr-selected-onLight)',
          },
          selectedHighlight: {
            DEFAULT: 'var(--mtr-selectedHighlight)',
            hover: 'var(--mtr-selectedHighlight_hover)',
          },
          focusBorder: {
            onLight: 'var(--mtr-focusBorder-onLight)',
            onDark: 'var(--mtr-focusBorder-onDark)',
          },
          scrim: 'var(--mtr-scrim)',
          navItemText: {
            'enabled-onLight': 'var(--mtr-navItemText-enabled-onLight)',
            'enabled-onDark': 'var(--mtr-navItemText-enabled-onDark)',
          },
          buttonToggleBg: {
            onLight: 'var(--mtr-buttonToggleBg-onLight)',
            onDark: 'var(--mtr-buttonToggleBg-onDark)',
          },
          chipBg: {
            enabled: 'var(--mtr-chipBg-enabled)',
            hover: 'var(--mtr-chipBg-hover)',
          },
          tableCellHighlight: {
            highEmphasis: 'var(--mtr-tableCellHighlight-highEmphasis)',
            midEmphasis: 'var(--mtr-tableCellHighlight-midEmphasis)',
          },
          grid: {
            finishedRowText: 'var(--mtr-grid-finishedRowText)',
            packageIconColor: 'var(--mtr-grid-packageIconColor)',
          },
        },
      },
    },
  },
  plugins: [],
};
